version: '3.8'

services:
  backend:
    build:
      context: ./good-works-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: admin
      DATABASE_PASSWORD: admin
      DATABASE_NAME: gwdb
    depends_on:
      - postgres
    networks:
      - my_network

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gwdb
    networks:
      - my_network
  frontend:
    build:
      context: ./good-works-front
      dockerfile: Dockerfile
    environment:
      BACKEND_ADDRES: backend
    ports:
      - "3003:80"
    networks:
      - my_network  
networks:
  my_network:
